from .main import MainController
from .about import AboutController
from .login import LoginController
from .student import StudentController
from .profile import ProfileController
from .password import PasswordController
from .grades import GradesController
from .sections import SectionsController
from .term_selection import TermSelectionController
from .search import SearchController
from .name_selection import NameSelectionController
from .register import RegisterController