from .main import MainController
from .about import AboutController
from .login import LoginController
from .student import StudentController
from .profile import ProfileController
from .password import PasswordController
from .grades import GradesController
from .schedule import ScheduleController
from .term_selection import TermSelectionController